# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
example <- function() {
    .Call('_ropengl_example', PACKAGE = 'ropengl')
}

#' @export
readFile <- function(name) {
    .Call('_ropengl_readFile', PACKAGE = 'ropengl', name)
}

#' @export
glfwInit <- function() {
    .Call('_ropengl_myGlfwInit', PACKAGE = 'ropengl')
}

#' @export
flip <- function() {
    invisible(.Call('_ropengl_flip', PACKAGE = 'ropengl'))
}

#' @export
ortho <- function(left, right, bottom, top, zNear, zFar) {
    .Call('_ropengl_ortho', PACKAGE = 'ropengl', left, right, bottom, top, zNear, zFar)
}

#' @export
perspective <- function(fov, aspect, zNear, zFar) {
    .Call('_ropengl_perspective', PACKAGE = 'ropengl', fov, aspect, zNear, zFar)
}

#' @export
frustum <- function(left, right, bottom, top, nearVal, farVal) {
    .Call('_ropengl_frustum', PACKAGE = 'ropengl', left, right, bottom, top, nearVal, farVal)
}

#' @export
identity <- function() {
    .Call('_ropengl_identity', PACKAGE = 'ropengl')
}

#' @export
lookAt <- function(eye, center, up) {
    .Call('_ropengl_lookAt', PACKAGE = 'ropengl', eye, center, up)
}

#' @export
scale <- function(mat, vec) {
    .Call('_ropengl_scale', PACKAGE = 'ropengl', mat, vec)
}

#' @export
translate <- function(mat, vec) {
    .Call('_ropengl_translate', PACKAGE = 'ropengl', mat, vec)
}

#' @export
rotate <- function(mat, angle, vec) {
    .Call('_ropengl_rotate', PACKAGE = 'ropengl', mat, angle, vec)
}

#' @export
normalize <- function(vec) {
    .Call('_ropengl_normalize', PACKAGE = 'ropengl', vec)
}

#' @export
cross <- function(a, b) {
    .Call('_ropengl_cross', PACKAGE = 'ropengl', a, b)
}

#' @export
getKeyId <- function(name) {
    .Call('_ropengl_getKeyId', PACKAGE = 'ropengl', name)
}

#' @export
getKeyByName <- function(name) {
    .Call('_ropengl_getKeyByName', PACKAGE = 'ropengl', name)
}

#' @export
getKeyName <- function(id) {
    .Call('_ropengl_myGlfwGetKeyName', PACKAGE = 'ropengl', id)
}

#' @export
getKeyById <- function(id) {
    .Call('_ropengl_getKeyById', PACKAGE = 'ropengl', id)
}

#' @export
initKeyMap <- function() {
    invisible(.Call('_ropengl_initKeyMap', PACKAGE = 'ropengl'))
}

#' @export
hideCursor <- function() {
    invisible(.Call('_ropengl_hideCursor', PACKAGE = 'ropengl'))
}

#' @export
showCursor <- function() {
    invisible(.Call('_ropengl_showCursor', PACKAGE = 'ropengl'))
}

#' @export
getCursorPos <- function() {
    .Call('_ropengl_getCursorPos', PACKAGE = 'ropengl')
}

#' @export
setCursorPos <- function(x, y) {
    invisible(.Call('_ropengl_setCursorPos', PACKAGE = 'ropengl', x, y))
}

#' @export
getMouseButtons <- function() {
    .Call('_ropengl_getMouseButtons', PACKAGE = 'ropengl')
}

#' @export
getScrollWheel <- function() {
    .Call('_ropengl_getScrollWheel', PACKAGE = 'ropengl')
}

#' Create new graphics window
#' @param x desired window width
#' @param y desired window height
#' @param name desired window name
#' @param fullScreen whether or not window is full screen
#' @export
createWindow <- function(x, y, name, fullScreen = FALSE) {
    invisible(.Call('_ropengl_createWindow', PACKAGE = 'ropengl', x, y, name, fullScreen))
}

#' Focus input on graphics window
#' 
#' @export
focusWindow <- function() {
    invisible(.Call('_ropengl_focusWindow', PACKAGE = 'ropengl'))
}

#' Close graphics window
#' 
#' @export
closeWindow <- function() {
    invisible(.Call('_ropengl_closeWindow', PACKAGE = 'ropengl'))
}

#' Is (x) button clicked on graphics window
#' 
#' @export
shouldWindowClose <- function() {
    .Call('_ropengl_shouldWindowClose', PACKAGE = 'ropengl')
}

#' @export
getFlag <- function(a) {
    .Call('_ropengl_getFlag', PACKAGE = 'ropengl', a)
}

#' @export
getFlagsOR <- function(a, b) {
    .Call('_ropengl_getFlagsOR', PACKAGE = 'ropengl', a, b)
}

#' @export
glShaderSource <- function(shader, a, count = 1L) {
    invisible(.Call('_ropengl_myGlShaderSource', PACKAGE = 'ropengl', shader, a, count))
}

#' @export
glGenVertexArrays <- function(n) {
    .Call('_ropengl_myGlGenVertexArrays', PACKAGE = 'ropengl', n)
}

#' @export
glDeleteVertexArrays <- function(n, arrays) {
    invisible(.Call('_ropengl_myGlDeleteVertexArrays', PACKAGE = 'ropengl', n, arrays))
}

#' @export
glBindVertexArray <- function(array) {
    invisible(.Call('_ropengl_myGlBindVertexArray', PACKAGE = 'ropengl', array))
}

#' @export
glActiveTexture <- function(texture) {
    invisible(.Call('_ropengl_myGlActiveTexture', PACKAGE = 'ropengl', texture))
}

#' @export
glAttachShader <- function(program, shader) {
    invisible(.Call('_ropengl_myGlAttachShader', PACKAGE = 'ropengl', program, shader))
}

#' @export
glBindAttribLocation <- function(program, index, name) {
    invisible(.Call('_ropengl_myGlBindAttribLocation', PACKAGE = 'ropengl', program, index, name))
}

#' @export
glBindBuffer <- function(target, buffer) {
    invisible(.Call('_ropengl_myGlBindBuffer', PACKAGE = 'ropengl', target, buffer))
}

#' @export
glBindFramebuffer <- function(target, framebuffer) {
    invisible(.Call('_ropengl_myGlBindFramebuffer', PACKAGE = 'ropengl', target, framebuffer))
}

#' @export
glBindRenderbuffer <- function(target, renderbuffer) {
    invisible(.Call('_ropengl_myGlBindRenderbuffer', PACKAGE = 'ropengl', target, renderbuffer))
}

#' @export
glBindTexture <- function(target, texture) {
    invisible(.Call('_ropengl_myGlBindTexture', PACKAGE = 'ropengl', target, texture))
}

#' @export
glBlendColor <- function(red, green, blue, alpha) {
    invisible(.Call('_ropengl_myGlBlendColor', PACKAGE = 'ropengl', red, green, blue, alpha))
}

#' @export
glBlendEquation <- function(mode) {
    invisible(.Call('_ropengl_myGlBlendEquation', PACKAGE = 'ropengl', mode))
}

#' @export
glBlendEquationSeparate <- function(modeRGB, modeAlpha) {
    invisible(.Call('_ropengl_myGlBlendEquationSeparate', PACKAGE = 'ropengl', modeRGB, modeAlpha))
}

#' @export
glBlendFunc <- function(sfactor, dfactor) {
    invisible(.Call('_ropengl_myGlBlendFunc', PACKAGE = 'ropengl', sfactor, dfactor))
}

#' @export
glBlendFuncSeparate <- function(sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha) {
    invisible(.Call('_ropengl_myGlBlendFuncSeparate', PACKAGE = 'ropengl', sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha))
}

#' @export
glBufferData <- function(target, data, usage, elementArray = FALSE) {
    invisible(.Call('_ropengl_myGlBufferData', PACKAGE = 'ropengl', target, data, usage, elementArray))
}

#' @export
glBufferSubData <- function(target, offset, size, data) {
    invisible(.Call('_ropengl_myGlBufferSubData', PACKAGE = 'ropengl', target, offset, size, data))
}

#' @export
glCheckFramebufferStatus <- function(target) {
    .Call('_ropengl_myGlCheckFramebufferStatus', PACKAGE = 'ropengl', target)
}

#' @export
glClear <- function(mask) {
    invisible(.Call('_ropengl_myGlClear', PACKAGE = 'ropengl', mask))
}

#' @export
glClearColor <- function(red, green, blue, alpha) {
    invisible(.Call('_ropengl_myGlClearColor', PACKAGE = 'ropengl', red, green, blue, alpha))
}

#' @export
glClearDepthf <- function(d) {
    invisible(.Call('_ropengl_myGlClearDepthf', PACKAGE = 'ropengl', d))
}

#' @export
glClearStencil <- function(s) {
    invisible(.Call('_ropengl_myGlClearStencil', PACKAGE = 'ropengl', s))
}

#' @export
glColorMask <- function(red, green, blue, alpha) {
    invisible(.Call('_ropengl_myGlColorMask', PACKAGE = 'ropengl', red, green, blue, alpha))
}

#' @export
glCompileShader <- function(shader) {
    invisible(.Call('_ropengl_myGlCompileShader', PACKAGE = 'ropengl', shader))
}

#' @export
glCompressedTexImage2D <- function(target, level, internalformat, width, height, border, imageSize, data) {
    invisible(.Call('_ropengl_myGlCompressedTexImage2D', PACKAGE = 'ropengl', target, level, internalformat, width, height, border, imageSize, data))
}

#' @export
glCompressedTexSubImage2D <- function(target, level, xoffset, yoffset, width, height, format, imageSize, data) {
    invisible(.Call('_ropengl_myGlCompressedTexSubImage2D', PACKAGE = 'ropengl', target, level, xoffset, yoffset, width, height, format, imageSize, data))
}

#' @export
glCopyTexImage2D <- function(target, level, internalformat, x, y, width, height, border) {
    invisible(.Call('_ropengl_myGlCopyTexImage2D', PACKAGE = 'ropengl', target, level, internalformat, x, y, width, height, border))
}

#' @export
glCopyTexSubImage2D <- function(target, level, xoffset, yoffset, x, y, width, height) {
    invisible(.Call('_ropengl_myGlCopyTexSubImage2D', PACKAGE = 'ropengl', target, level, xoffset, yoffset, x, y, width, height))
}

#' @export
glCreateProgram <- function() {
    .Call('_ropengl_myGlCreateProgram', PACKAGE = 'ropengl')
}

#' @export
glCreateShader <- function(type) {
    .Call('_ropengl_myGlCreateShader', PACKAGE = 'ropengl', type)
}

#' @export
glCullFace <- function(mode) {
    invisible(.Call('_ropengl_myGlCullFace', PACKAGE = 'ropengl', mode))
}

#' @export
glDeleteBuffers <- function(n, buffers) {
    invisible(.Call('_ropengl_myGlDeleteBuffers', PACKAGE = 'ropengl', n, buffers))
}

#' @export
glDeleteFramebuffers <- function(n, framebuffers) {
    invisible(.Call('_ropengl_myGlDeleteFramebuffers', PACKAGE = 'ropengl', n, framebuffers))
}

#' @export
glDeleteProgram <- function(program) {
    invisible(.Call('_ropengl_myGlDeleteProgram', PACKAGE = 'ropengl', program))
}

#' @export
glDeleteRenderbuffers <- function(n, renderbuffers) {
    invisible(.Call('_ropengl_myGlDeleteRenderbuffers', PACKAGE = 'ropengl', n, renderbuffers))
}

#' @export
glDeleteShader <- function(shader) {
    invisible(.Call('_ropengl_myGlDeleteShader', PACKAGE = 'ropengl', shader))
}

#' @export
glDeleteTextures <- function(n, textures) {
    invisible(.Call('_ropengl_myGlDeleteTextures', PACKAGE = 'ropengl', n, textures))
}

#' @export
glDepthFunc <- function(func) {
    invisible(.Call('_ropengl_myGlDepthFunc', PACKAGE = 'ropengl', func))
}

#' @export
glDepthMask <- function(flag) {
    invisible(.Call('_ropengl_myGlDepthMask', PACKAGE = 'ropengl', flag))
}

#' @export
glDepthRangef <- function(n, f) {
    invisible(.Call('_ropengl_myGlDepthRangef', PACKAGE = 'ropengl', n, f))
}

#' @export
glDetachShader <- function(program, shader) {
    invisible(.Call('_ropengl_myGlDetachShader', PACKAGE = 'ropengl', program, shader))
}

#' @export
glDisable <- function(cap) {
    invisible(.Call('_ropengl_myGlDisable', PACKAGE = 'ropengl', cap))
}

#' @export
glDisableVertexAttribArray <- function(index) {
    invisible(.Call('_ropengl_myGlDisableVertexAttribArray', PACKAGE = 'ropengl', index))
}

#' @export
glDrawArrays <- function(mode, first, count) {
    invisible(.Call('_ropengl_myGlDrawArrays', PACKAGE = 'ropengl', mode, first, count))
}

#' @export
glDrawElements <- function(mode, count, type) {
    invisible(.Call('_ropengl_myGlDrawElements', PACKAGE = 'ropengl', mode, count, type))
}

#' @export
glEnable <- function(cap) {
    invisible(.Call('_ropengl_myGlEnable', PACKAGE = 'ropengl', cap))
}

#' @export
glEnableVertexAttribArray <- function(index) {
    invisible(.Call('_ropengl_myGlEnableVertexAttribArray', PACKAGE = 'ropengl', index))
}

#' @export
glFinish <- function() {
    invisible(.Call('_ropengl_myGlFinish', PACKAGE = 'ropengl'))
}

#' @export
glFlush <- function() {
    invisible(.Call('_ropengl_myGlFlush', PACKAGE = 'ropengl'))
}

#' @export
glFramebufferRenderbuffer <- function(target, attachment, renderbuffertarget, renderbuffer) {
    invisible(.Call('_ropengl_myGlFramebufferRenderbuffer', PACKAGE = 'ropengl', target, attachment, renderbuffertarget, renderbuffer))
}

#' @export
glFramebufferTexture2D <- function(target, attachment, textarget, texture, level) {
    invisible(.Call('_ropengl_myGlFramebufferTexture2D', PACKAGE = 'ropengl', target, attachment, textarget, texture, level))
}

#' @export
glFrontFace <- function(mode) {
    invisible(.Call('_ropengl_myGlFrontFace', PACKAGE = 'ropengl', mode))
}

#' @export
glGenBuffers <- function(n) {
    .Call('_ropengl_myGlGenBuffers', PACKAGE = 'ropengl', n)
}

#' @export
glGenerateMipmap <- function(target) {
    invisible(.Call('_ropengl_myGlGenerateMipmap', PACKAGE = 'ropengl', target))
}

#' @export
glGenFramebuffers <- function(n) {
    .Call('_ropengl_myGlGenFramebuffers', PACKAGE = 'ropengl', n)
}

#' @export
glGenRenderbuffers <- function(n) {
    .Call('_ropengl_myGlGenRenderbuffers', PACKAGE = 'ropengl', n)
}

#' @export
glGenTextures <- function(n) {
    .Call('_ropengl_myGlGenTextures', PACKAGE = 'ropengl', n)
}

#' @export
glGetAttribLocation <- function(program, name) {
    .Call('_ropengl_myGlGetAttribLocation', PACKAGE = 'ropengl', program, name)
}

#' @export
glGetBufferParameteriv <- function(target, pname, n = 1L) {
    .Call('_ropengl_myGlGetBufferParameteriv', PACKAGE = 'ropengl', target, pname, n)
}

#' @export
glGetError <- function() {
    .Call('_ropengl_myGlGetError', PACKAGE = 'ropengl')
}

#' @export
glGetFloatv <- function(pname, n = 1L) {
    .Call('_ropengl_myGlGetFloatv', PACKAGE = 'ropengl', pname, n)
}

#' @export
glGetFramebufferAttachmentParameteriv <- function(target, attachment, pname, n = 1L) {
    .Call('_ropengl_myGlGetFramebufferAttachmentParameteriv', PACKAGE = 'ropengl', target, attachment, pname, n)
}

#' @export
glGetIntegerv <- function(pname, n = 1L) {
    .Call('_ropengl_myGlGetIntegerv', PACKAGE = 'ropengl', pname, n)
}

#' @export
glGetProgramiv <- function(program, pname, n = 1L) {
    .Call('_ropengl_myGlGetProgramiv', PACKAGE = 'ropengl', program, pname, n)
}

#' @export
glGetRenderbufferParameteriv <- function(target, pname, n = 1L) {
    .Call('_ropengl_myGlGetRenderbufferParameteriv', PACKAGE = 'ropengl', target, pname, n)
}

#' @export
glGetShaderiv <- function(shader, pname, n = 1L) {
    .Call('_ropengl_myGlGetShaderiv', PACKAGE = 'ropengl', shader, pname, n)
}

#' @export
glGetTexParameterfv <- function(target, pname, n = 1L) {
    .Call('_ropengl_myGlGetTexParameterfv', PACKAGE = 'ropengl', target, pname, n)
}

#' @export
glGetTexParameteriv <- function(target, pname, n = 1L) {
    .Call('_ropengl_myGlGetTexParameteriv', PACKAGE = 'ropengl', target, pname, n)
}

#' @export
glGetUniformfv <- function(program, location, n = 1L) {
    .Call('_ropengl_myGlGetUniformfv', PACKAGE = 'ropengl', program, location, n)
}

#' @export
glGetUniformiv <- function(program, location, n = 1L) {
    .Call('_ropengl_myGlGetUniformiv', PACKAGE = 'ropengl', program, location, n)
}

#' @export
glGetUniformLocation <- function(program, name) {
    .Call('_ropengl_myGlGetUniformLocation', PACKAGE = 'ropengl', program, name)
}

#' @export
glGetVertexAttribfv <- function(index, pname, n = 1L) {
    .Call('_ropengl_myGlGetVertexAttribfv', PACKAGE = 'ropengl', index, pname, n)
}

#' @export
glGetVertexAttribiv <- function(index, pname, n = 1L) {
    .Call('_ropengl_myGlGetVertexAttribiv', PACKAGE = 'ropengl', index, pname, n)
}

#' @export
glHint <- function(target, mode) {
    invisible(.Call('_ropengl_myGlHint', PACKAGE = 'ropengl', target, mode))
}

#' @export
glIsBuffer <- function(buffer) {
    .Call('_ropengl_myGlIsBuffer', PACKAGE = 'ropengl', buffer)
}

#' @export
glIsEnabled <- function(cap) {
    .Call('_ropengl_myGlIsEnabled', PACKAGE = 'ropengl', cap)
}

#' @export
glIsFramebuffer <- function(framebuffer) {
    .Call('_ropengl_myGlIsFramebuffer', PACKAGE = 'ropengl', framebuffer)
}

#' @export
glIsProgram <- function(program) {
    .Call('_ropengl_myGlIsProgram', PACKAGE = 'ropengl', program)
}

#' @export
glIsRenderbuffer <- function(renderbuffer) {
    .Call('_ropengl_myGlIsRenderbuffer', PACKAGE = 'ropengl', renderbuffer)
}

#' @export
glIsShader <- function(shader) {
    .Call('_ropengl_myGlIsShader', PACKAGE = 'ropengl', shader)
}

#' @export
glIsTexture <- function(texture) {
    .Call('_ropengl_myGlIsTexture', PACKAGE = 'ropengl', texture)
}

#' @export
glLineWidth <- function(width) {
    invisible(.Call('_ropengl_myGlLineWidth', PACKAGE = 'ropengl', width))
}

#' @export
glLinkProgram <- function(program) {
    invisible(.Call('_ropengl_myGlLinkProgram', PACKAGE = 'ropengl', program))
}

#' @export
glPixelStorei <- function(pname, param) {
    invisible(.Call('_ropengl_myGlPixelStorei', PACKAGE = 'ropengl', pname, param))
}

#' @export
glPolygonOffset <- function(factor, units) {
    invisible(.Call('_ropengl_myGlPolygonOffset', PACKAGE = 'ropengl', factor, units))
}

#' @export
glReadPixels <- function(x, y, width, height, format, type, n = 1L) {
    .Call('_ropengl_myGlReadPixels', PACKAGE = 'ropengl', x, y, width, height, format, type, n)
}

#' @export
glReleaseShaderCompiler <- function() {
    invisible(.Call('_ropengl_myGlReleaseShaderCompiler', PACKAGE = 'ropengl'))
}

#' @export
glRenderbufferStorage <- function(target, internalformat, width, height) {
    invisible(.Call('_ropengl_myGlRenderbufferStorage', PACKAGE = 'ropengl', target, internalformat, width, height))
}

#' @export
glSampleCoverage <- function(value, invert) {
    invisible(.Call('_ropengl_myGlSampleCoverage', PACKAGE = 'ropengl', value, invert))
}

#' @export
glScissor <- function(x, y, width, height) {
    invisible(.Call('_ropengl_myGlScissor', PACKAGE = 'ropengl', x, y, width, height))
}

#' @export
glStencilFunc <- function(func, ref, mask) {
    invisible(.Call('_ropengl_myGlStencilFunc', PACKAGE = 'ropengl', func, ref, mask))
}

#' @export
glStencilFuncSeparate <- function(face, func, ref, mask) {
    invisible(.Call('_ropengl_myGlStencilFuncSeparate', PACKAGE = 'ropengl', face, func, ref, mask))
}

#' @export
glStencilMask <- function(mask) {
    invisible(.Call('_ropengl_myGlStencilMask', PACKAGE = 'ropengl', mask))
}

#' @export
glStencilMaskSeparate <- function(face, mask) {
    invisible(.Call('_ropengl_myGlStencilMaskSeparate', PACKAGE = 'ropengl', face, mask))
}

#' @export
glStencilOp <- function(fail, zfail, zpass) {
    invisible(.Call('_ropengl_myGlStencilOp', PACKAGE = 'ropengl', fail, zfail, zpass))
}

#' @export
glStencilOpSeparate <- function(face, sfail, dpfail, dppass) {
    invisible(.Call('_ropengl_myGlStencilOpSeparate', PACKAGE = 'ropengl', face, sfail, dpfail, dppass))
}

#' @export
glTexImage2D <- function(fname) {
    invisible(.Call('_ropengl_myGlTexImage2D', PACKAGE = 'ropengl', fname))
}

#' @export
glTexParameterf <- function(target, pname, param) {
    invisible(.Call('_ropengl_myGlTexParameterf', PACKAGE = 'ropengl', target, pname, param))
}

#' @export
glTexParameterfv <- function(target, pname, params) {
    invisible(.Call('_ropengl_myGlTexParameterfv', PACKAGE = 'ropengl', target, pname, params))
}

#' @export
glTexParameteri <- function(target, pname, param) {
    invisible(.Call('_ropengl_myGlTexParameteri', PACKAGE = 'ropengl', target, pname, param))
}

#' @export
glTexParameteriv <- function(target, pname, params) {
    invisible(.Call('_ropengl_myGlTexParameteriv', PACKAGE = 'ropengl', target, pname, params))
}

#' @export
glTexSubImage2D <- function(target, level, xoffset, yoffset, width, height, format, type, pixels) {
    invisible(.Call('_ropengl_myGlTexSubImage2D', PACKAGE = 'ropengl', target, level, xoffset, yoffset, width, height, format, type, pixels))
}

#' @export
glUniform1f <- function(location, v0) {
    invisible(.Call('_ropengl_myGlUniform1f', PACKAGE = 'ropengl', location, v0))
}

#' @export
glUniform1fv <- function(location, count, value) {
    invisible(.Call('_ropengl_myGlUniform1fv', PACKAGE = 'ropengl', location, count, value))
}

#' @export
glUniform1i <- function(location, v0) {
    invisible(.Call('_ropengl_myGlUniform1i', PACKAGE = 'ropengl', location, v0))
}

#' @export
glUniform1iv <- function(location, count, value) {
    invisible(.Call('_ropengl_myGlUniform1iv', PACKAGE = 'ropengl', location, count, value))
}

#' @export
glUniform2f <- function(location, v0, v1) {
    invisible(.Call('_ropengl_myGlUniform2f', PACKAGE = 'ropengl', location, v0, v1))
}

#' @export
glUniform2fv <- function(location, count, value) {
    invisible(.Call('_ropengl_myGlUniform2fv', PACKAGE = 'ropengl', location, count, value))
}

#' @export
glUniform2i <- function(location, v0, v1) {
    invisible(.Call('_ropengl_myGlUniform2i', PACKAGE = 'ropengl', location, v0, v1))
}

#' @export
glUniform2iv <- function(location, count, value) {
    invisible(.Call('_ropengl_myGlUniform2iv', PACKAGE = 'ropengl', location, count, value))
}

#' @export
glUniform3f <- function(location, v0, v1, v2) {
    invisible(.Call('_ropengl_myGlUniform3f', PACKAGE = 'ropengl', location, v0, v1, v2))
}

#' @export
glUniform3fv <- function(location, count, value) {
    invisible(.Call('_ropengl_myGlUniform3fv', PACKAGE = 'ropengl', location, count, value))
}

#' @export
glUniform3i <- function(location, v0, v1, v2) {
    invisible(.Call('_ropengl_myGlUniform3i', PACKAGE = 'ropengl', location, v0, v1, v2))
}

#' @export
glUniform3iv <- function(location, count, value) {
    invisible(.Call('_ropengl_myGlUniform3iv', PACKAGE = 'ropengl', location, count, value))
}

#' @export
glUniform4f <- function(location, v0, v1, v2, v3) {
    invisible(.Call('_ropengl_myGlUniform4f', PACKAGE = 'ropengl', location, v0, v1, v2, v3))
}

#' @export
glUniform4fv <- function(location, count, value) {
    invisible(.Call('_ropengl_myGlUniform4fv', PACKAGE = 'ropengl', location, count, value))
}

#' @export
glUniform4i <- function(location, v0, v1, v2, v3) {
    invisible(.Call('_ropengl_myGlUniform4i', PACKAGE = 'ropengl', location, v0, v1, v2, v3))
}

#' @export
glUniform4iv <- function(location, count, value) {
    invisible(.Call('_ropengl_myGlUniform4iv', PACKAGE = 'ropengl', location, count, value))
}

#' @export
glUniformMatrix2fv <- function(location, count, transpose, value) {
    invisible(.Call('_ropengl_myGlUniformMatrix2fv', PACKAGE = 'ropengl', location, count, transpose, value))
}

#' @export
glUniformMatrix3fv <- function(location, count, transpose, value) {
    invisible(.Call('_ropengl_myGlUniformMatrix3fv', PACKAGE = 'ropengl', location, count, transpose, value))
}

#' @export
glUniformMatrix4fv <- function(location, count, transpose, mat) {
    invisible(.Call('_ropengl_myGlUniformMatrix4fv', PACKAGE = 'ropengl', location, count, transpose, mat))
}

#' @export
glUseProgram <- function(program) {
    invisible(.Call('_ropengl_myGlUseProgram', PACKAGE = 'ropengl', program))
}

#' @export
glValidateProgram <- function(program) {
    invisible(.Call('_ropengl_myGlValidateProgram', PACKAGE = 'ropengl', program))
}

#' @export
glVertexAttrib1f <- function(index, x) {
    invisible(.Call('_ropengl_myGlVertexAttrib1f', PACKAGE = 'ropengl', index, x))
}

#' @export
glVertexAttrib1fv <- function(index, v) {
    invisible(.Call('_ropengl_myGlVertexAttrib1fv', PACKAGE = 'ropengl', index, v))
}

#' @export
glVertexAttrib2f <- function(index, x, y) {
    invisible(.Call('_ropengl_myGlVertexAttrib2f', PACKAGE = 'ropengl', index, x, y))
}

#' @export
glVertexAttrib2fv <- function(index, v) {
    invisible(.Call('_ropengl_myGlVertexAttrib2fv', PACKAGE = 'ropengl', index, v))
}

#' @export
glVertexAttrib3f <- function(index, x, y, z) {
    invisible(.Call('_ropengl_myGlVertexAttrib3f', PACKAGE = 'ropengl', index, x, y, z))
}

#' @export
glVertexAttrib3fv <- function(index, v) {
    invisible(.Call('_ropengl_myGlVertexAttrib3fv', PACKAGE = 'ropengl', index, v))
}

#' @export
glVertexAttrib4f <- function(index, x, y, z, w) {
    invisible(.Call('_ropengl_myGlVertexAttrib4f', PACKAGE = 'ropengl', index, x, y, z, w))
}

#' @export
glVertexAttrib4fv <- function(index, v) {
    invisible(.Call('_ropengl_myGlVertexAttrib4fv', PACKAGE = 'ropengl', index, v))
}

#' @export
glVertexAttribPointer <- function(index, size, type, normalized, stride, pointer) {
    invisible(.Call('_ropengl_myGlVertexAttribPointer', PACKAGE = 'ropengl', index, size, type, normalized, stride, pointer))
}

#' @export
glViewport <- function(x, y, width, height) {
    invisible(.Call('_ropengl_myGlViewport', PACKAGE = 'ropengl', x, y, width, height))
}

